# â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ•—â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ•— â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ•— â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ•— â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ•—â–ˆâ–ˆâ•—  â–ˆâ–ˆâ•—â–ˆâ–ˆâ•—â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ•—
# â–ˆâ–ˆâ•”â•â•â•â•â•â•šâ•â•â–ˆâ–ˆâ•”â•â•â•â–ˆâ–ˆâ•”â•â•â–ˆâ–ˆâ•—â–ˆâ–ˆâ•”â•â•â–ˆâ–ˆâ•—â–ˆâ–ˆâ•”â•â•â•â•â•â–ˆâ–ˆâ•‘  â–ˆâ–ˆâ•‘â–ˆâ–ˆâ•‘â–ˆâ–ˆâ•”â•â•â–ˆâ–ˆâ•—
# â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ•—   â–ˆâ–ˆâ•‘   â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ•‘â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ•”â•â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ•—â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ•‘â–ˆâ–ˆâ•‘â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ•”â•
# â•šâ•â•â•â•â–ˆâ–ˆâ•‘   â–ˆâ–ˆâ•‘   â–ˆâ–ˆâ•”â•â•â–ˆâ–ˆâ•‘â–ˆâ–ˆâ•”â•â•â–ˆâ–ˆâ•—â•šâ•â•â•â•â–ˆâ–ˆâ•‘â–ˆâ–ˆâ•”â•â•â–ˆâ–ˆâ•‘â–ˆâ–ˆâ•‘â–ˆâ–ˆâ•”â•â•â•â•
# â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ•‘   â–ˆâ–ˆâ•‘   â–ˆâ–ˆâ•‘  â–ˆâ–ˆâ•‘â–ˆâ–ˆâ•‘  â–ˆâ–ˆâ•‘â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ•‘â–ˆâ–ˆâ•‘  â–ˆâ–ˆâ•‘â–ˆâ–ˆâ•‘â–ˆâ–ˆâ•‘
# â•šâ•â•â•â•â•â•â•   â•šâ•â•   â•šâ•â•  â•šâ•â•â•šâ•â•  â•šâ•â•â•šâ•â•â•â•â•â•â•â•šâ•â•  â•šâ•â•â•šâ•â•â•šâ•â•

# Inserts a blank line between shell prompts
add_newline = false

# Change command timeout from 500 to 1000 ms
command_timeout = 1000

#     ______                           __
#    / ____/___  _________ ___  ____ _/ /_
#   / /_  / __ \/ ___/ __ `__ \/ __ `/ __/
#  / __/ / /_/ / /  / / / / / / /_/ / /_
# /_/    \____/_/  /_/ /_/ /_/\__,_/\__/

format = """
[â•­â•¼](8)[î‚¶](0)$os$hostname$shell$username$sudo[î‚´](fg:0 bg:6)$directory[î‚´](fg:6 bg:0)$git_branch$git_commit$git_state$git_metrics$git_status[î‚´]\
(fg:0)$fill[î‚¶](0)$cmd_duration$jobs$battery$memory_usage$localip[î‚´](fg:0 bg:8)$time[î‚´](fg:8 bg:none)$line_break[â•°â•¼](8)$character"""

# Connecter between shell and sudo in the left prompt line 1
# [âŸ ](bg:0 fg:8)\

[fill]
symbol = "â€”"

#      __         ______     ____                             __
#     / /   ___  / __/ /_   / __ \_________  ____ ___  ____  / /_
#    / /   / _ \/ /_/ __/  / /_/ / ___/ __ \/ __ `__ \/ __ \/ __/
#   / /___/  __/ __/ /_   / ____/ /  / /_/ / / / / / / /_/ / /_
#  /_____/\___/_/  \__/  /_/   /_/   \____/_/ /_/ /_/ .___/\__/
#                                                  /_/

# Line 1
[os]
disabled = false
format = "[$symbol](bg:0 fg:6)"
[os.symbols]
Alpine = "ïŒ€ "
Amazon = "ï‰° "
Android = "ï…» "
Arch = "ïŒƒ "
CentOS = "ïŒ„ "
Debian = "î½ "
DragonFly = "ğŸ‰ "
Emscripten = "ğŸ”— "
EndeavourOS = "ïŒ¢ "
Fedora = "ïŒŠ "
FreeBSD = "ïŒŒ "
Garuda = "ğŸ¦… "
Gentoo = "ïŒ "
HardenedBSD = "ğŸ›¡ï¸ "
Illumos = "ïŒ¦ "
Linux = "ï…¼ "
Macos = "ï”´ "
Manjaro = "ïŒ’ "
Mariner = "ğŸŒŠ "
MidnightBSD = "ğŸŒ˜ "
Mint = "ïŒ "
NetBSD = "ğŸš© "
NixOS = "ïŒ“ "
OpenBSD = "ğŸ¡ "
openSUSE = "ïŒ” "
OracleLinux = "ğŸ¦´ "
Pop = "ïŒª "
Raspbian = "ïŒ• "
Redhat = "ïŒ– "
RedHatEnterprise = "ïŒ– "
Redox = "ğŸ§ª "
Solus = "ïŒ­ "
SUSE = "ïŒ” "
Ubuntu = "ïŒ› "
Unknown = "ï…¼ "
Windows = "ï…º "

[shell]
disabled= false
style = "bg:0 fg:6 blink"
format = '[$indicator]($style)'
powershell_indicator = "î¯‡ "
bash_indicator = "î¯Š "
fish_indicator = "ïœ¹ "
zsh_indicator = "î­„ "
cmd_indicator = "î¯„ "

[hostname]
disabled = false
ssh_symbol = "î¬¹ "
ssh_only = false
style = "bg:0 fg:4 bold italic"
format = "[ $ssh_symbol$hostname ]($style)"

[sudo]
disabled = false
allow_windows = true
style = 'bg:0 fg:2'
format = "[$symbol]($style)"
symbol = 'îŠ† '

[username]
disabled = false
style_user = "bg:0 fg:5 bold"
style_root = "bg:0 fg:1 bold"
format = "[ $user ]($style)"
show_always = true

[directory]
disabled = false
read_only = " ï€£ "
read_only_style = "bg:6 fg:1"
truncation_length = 3
truncation_symbol = "â€¦/"
style = "bg:6 fg:0 bold"
format = "[ $path]($style)[$read_only]($read_only_style)"
home_symbol = "ï€• ~"
[directory.substitutions]
"Documents" = "ïœ˜ "
"Downloads" = "ï€™ "
"Music" = "ï€ "
"Pictures" = "ï€¾ "
".dotfiles" = "î—¼ "
"github" = "îœ‚ "

[git_branch]
disabled = false
symbol = "ï˜ "
format = "[ $symbol$branch ]($style)"
style = "bg:0 fg:2 bold"
truncation_length = 6
truncation_symbol = "â‹¯/"
only_attached = false

[git_commit]
disabled = false
commit_hash_length = 7
tag_symbol = "ğŸ”–"
tag_disabled = false
only_detached = false
style = "bg:0 fg:5"
format = "[($hash$tag)]($style)"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bg:1 fg:8"

[git_metrics]
disabled = true
added_style = "bg:0 fg:2 bold"
deleted_style = "bg:0 fg:1 bold"
only_nonzero_diffs = false
format = '[ +$added]($added_style)[ -$deleted]($deleted_style)'

[git_status]
disabled = false
format = '([$all_status$ahead_behind]($style))'
style = "bg:0 fg:6 bold"
conflicted = " ğŸ³"
up_to_date = ""
untracked = " ?"
ahead = " â‡¡${count}"
diverged = " â‡•â‡¡${ahead_count}â‡£${behind_count}"
behind = " â‡£${count}"
stashed = " $"
modified = " !"
staged = '[ +\($count\)](bg:0 fg:2)'
renamed = " Â»"
deleted = " âœ˜"
windows_starship = '/mnt/c/Program Files/starship/bin/starship.exe'

## Line 2
[character]
disabled = false
success_symbol = "[ï”](2)"
error_symbol = "[ï”](1)"
vicmd_symbol = "[â®](2)"
vimcmd_replace_one_symbol = "[â®](5)"
vimcmd_replace_symbol = "[â®](5)"
vimcmd_visual_symbol = "[â®](3)"

#      ____  _       __    __     ____                             __
#     / __ \(_)___ _/ /_  / /_   / __ \_________  ____ ___  ____  / /_
#    / /_/ / / __ `/ __ \/ __/  / /_/ / ___/ __ \/ __ `__ \/ __ \/ __/
#   / _, _/ / /_/ / / / / /_   / ____/ /  / /_/ / / / / / / /_/ / /_
#  /_/ |_/_/\__, /_/ /_/\__/  /_/   /_/   \____/_/ /_/ /_/ .___/\__/
#          /____/                                       /_/

# Line 1
[cmd_duration]
disabled = false
min_time = 2000
min_time_to_notify = 45000
show_milliseconds = false
show_notifications = true
style = "bg:0 fg:3"
format = '[âœ« $duration ]($style)'

[jobs]
disabled = false
symbol = "ï€“"
style = "bg:0 fg:1 bold"
symbol_threshold = 1
number_threshold = 2
format = "[$symbol$number]($style)"

[battery]
disabled = false
full_symbol = 'ğŸ”‹'
charging_symbol = 'âš¡ï¸ '
discharging_symbol = 'ğŸ’€'
unknown_symbol = "â“"
empty_symbol = "ğŸª« "
format = '[$symbol $percentage](bg:0 fg:$style)'
[[battery.display]]
threshold = 15
style = '1 bold blink'
[[battery.display]]
threshold = 25
style = '1 bold'
[[battery.display]]
threshold = 50
style = '3 bold'
[[battery.display]]
threshold = 75
style = '2 bold'
[[battery.display]]
threshold = 100
style = '10 bold'

[memory_usage]
disabled = false
symbol = "ï¡š "
threshold = 0
style = "bg:0 fg:12"
format = "[ $symbol$ram]($style)"

[localip]
disabled = false
ssh_only = false
format = '[ ï„¤ $localipv4](bg:0 fg:9 bold)'

[time]
disabled = false
time_format = "%T"
style = "bg:8 fg:7"
format = "[ ï€— $time ]($style)"
use_12hr = true